title: "Scalata Docs"
theme: "just-the-docs"
color_scheme: "dark"   # or "light"
footer_content: "© 2025 Scalata Project — PPS 24"
aux_links:
  "Scalata on GitHub":
    - "https://github.com/ferriforty/PPS-24-Scalata"

search: true
