source "https://rubygems.org"
gem "jekyll"
gem "csv"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "base64"
gem "bigdecimal"
gem "logger"
gem "rexml"
gem "github-pages", group: :jekyll_plugins
gem "fiddle"
gem "sass-embedded", "~> 1.58.0"

