name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [3.4.2]
        java: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Run tests
        run: sbt clean coverage test coverageReport

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/scala-3.4.2/scoverage-data/scoverage.xml
          fail_ci_if_error: true

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}